In [1]:
import pandas as pd

In [4]:
excel_orig = pd.read_excel('../2019_MCMProblemC_DATA/MCM_NFLIS_Data.xlsx', sheet_name='Data')

In [5]:
excel_orig.describe()

,YYYY,FIPS_State,FIPS_County,FIPS_Combined,DrugReports,TotalDrugReportsCounty,TotalDrugReportsState
count,24062.000000,24062.000000,24062.000000,24062.000000,24062.000000,24062.000000,24062.000000
mean,2013.719018,39.642715,114.497839,39757.212493,25.369545,991.824869,56083.943895
std,2.347137,11.288284,133.005612,11300.941194,145.808411,2598.556115,33602.211295
min,2010.000000,21.000000,1.000000,21001.000000,1.000000,1.000000,3672.000000
25%,2012.000000,39.000000,43.000000,39015.000000,1.000000,136.000000,28285.000000
50%,2014.000000,42.000000,87.000000,42005.000000,4.000000,314.000000,41462.000000
75%,2016.000000,51.000000,141.000000,51069.000000,13.000000,737.000000,78577.000000
max,2017.000000,54.000000,840.000000,54109.000000,5075.000000,33513.000000,119349.000000

按年份切分

In [17]:
alldata = []
alldata.append(excel_orig[excel_orig['YYYY'] == 2010])
alldata.append(excel_orig[excel_orig['YYYY'] == 2011])
alldata.append(excel_orig[excel_orig['YYYY'] == 2012])
alldata.append(excel_orig[excel_orig['YYYY'] == 2013])
alldata.append(excel_orig[excel_orig['YYYY'] == 2014])
alldata.append(excel_orig[excel_orig['YYYY'] == 2015])
alldata.append(excel_orig[excel_orig['YYYY'] == 2016])
alldata.append(excel_orig[excel_orig['YYYY'] == 2017])

In [18]:
sum([len(d) for d in alldata])

24062

所有县的代码

In [19]:
all_counties = set(excel_orig['FIPS_Combined'].tolist())
len(all_counties)

461

In [69]:
totalNum = 0
county2drugtotals = []
countyCode2Name = {}
for d in alldata:
    countytotal = {}
    for i in range(len(d)):
        data = d.iloc[i]
        countytotal[data['FIPS_Combined']] = data['TotalDrugReportsCounty']
        countyCode2Name[data['FIPS_Combined']] = data['State'] + ', ' + data['COUNTY']
    county2drugtotals.append(countytotal)
    totalNum += len(countytotal)
print('Total: {}'.format(totalNum))

Total: 3480

name2Code: 名字对应代码
countyCode2Name: 代码对应名字

In [88]:
Name2Code = {v: k for k, v in countyCode2Name.items()}

In [53]:
for countyTotal in county2drugtotals:
    for c in all_counties:
        if c not in countyTotal.keys():
            countyTotal[c] = 0

In [99]:
county2drugtotals[0]

{51001: 84,
 39001: 527,
 42001: 334,
 51510: 427,
 42003: 8500,
 21003: 168,
 51007: 94,
 51013: 610,
 42005: 344,
 39005: 766,
 39007: 571,
 39009: 664,
 39011: 184,
 54001: 16,
 21009: 383,
 21011: 81,
 42009: 150,
 51019: 177,
 21013: 387,
 54003: 722,
 42011: 2146,
 51021: 25,
 21015: 299,
 54005: 90,
 21023: 28,
 54007: 167,
 21025: 162,
 21027: 78,
 39015: 213,
 51029: 136,
 42017: 6140,
 21029: 316,
 39017: 1825,
 42019: 310,
 54011: 517,
 54013: 8,
 42021: 483,
 42023: 7,
 42025: 209,
 51033: 138,
 21041: 99,
 39019: 57,
 21043: 354,
 21045: 148,
 51540: 264,
 51550: 881,
 42029: 1979,
 51041: 1331,
 21047: 439,
 42031: 221,
 42033: 218,
 39025: 752,
 39027: 455,
 51570: 190,
 42037: 131,
 39029: 341,
 39033: 218,
 42039: 433,
 21055: 34,
 39035: 3556,
 51590: 332,
 42043: 2575,
 21059: 591,
 39039: 589,
 39041: 1774,
 42045: 4534,
 51051: 103,
 54017: 16,
 39043: 552,
 42049: 1570,
 51057: 94,
 51059: 3337,
 21001: 88,
 51003: 282,
 51005: 154,
 39003: 580,
 51009: 411,
 51015: 344,
 51017: 40,
 42007: 625,
 39013: 231,
 21017: 161,
 21019: 504,
 21021: 200,
 51520: 276,
 51027: 185,
 51530: 44,
 21035: 97,
 21037: 852,
 51031: 209,
 51035: 166,
 42027: 1028,
 39021: 214,
 21049: 214,
 51043: 35,
 21051: 208,
 21053: 75,
 42035: 118,
 39031: 75,
 51045: 69,
 51047: 492,
 21057: 17,
 51049: 64,
 39037: 156,
 51053: 131,
 21063: 91,
 51600: 148,
 39045: 846,
 21005: 98,
 51515: 4,
 42013: 662,
 51023: 175,
 42015: 145,
 51037: 75,
 42041: 310,
 42047: 123,
 51595: 91,
 21065: 85,
 54009: 9,
 21031: 102,
 21039: 26,
 39023: 186,
 54015: 50,
 21007: 24,
 51025: 131,
 21033: 78,
 51610: 65,
 21067: 1967,
 21061: 78,
 51061: 418,
 51011: 39,
 39047: 95,
 42051: 859,
 21071: 306,
 51063: 78,
 51065: 50,
 21073: 430,
 39049: 2921,
 42055: 755,
 51067: 255,
 51069: 401,
 21075: 74,
 42057: 122,
 51640: 31,
 39053: 416,
 39055: 114,
 51071: 241,
 51073: 133,
 51075: 49,
 21081: 133,
 54023: 95,
 21083: 217,
 21085: 257,
 51077: 103,
 54025: 254,
 39057: 964,
 42059: 179,
 51079: 102,
 39059: 316,
 51083: 277,
 39061: 13780,
 51650: 775,
 39063: 573,
 51085: 510,
 39065: 326,
 54031: 76,
 54033: 196,
 51660: 48,
 21099: 76,
 21101: 222,
 51087: 1154,
 51089: 164,
 39075: 129,
 21107: 249,
 42061: 174,
 39077: 240,
 42063: 604,
 39079: 632,
 54035: 116,
 51095: 237,
 21111: 5426,
 39081: 264,
 42065: 200,
 54037: 133,
 21115: 243,
 21117: 1073,
 51099: 128,
 51101: 48,
 21119: 284,
 21121: 483,
 39083: 31,
 42069: 1123,
 39085: 2726,
 42071: 1683,
 21125: 623,
 42075: 648,
 42077: 2385,
 39089: 1639,
 21141: 111,
 39091: 273,
 54045: 307,
 51107: 902,
 51109: 184,
 21069: 88,
 51620: 64,
 51630: 234,
 39051: 65,
 21079: 77,
 21087: 59,
 51081: 112,
 21089: 108,
 54029: 152,
 21095: 419,
 21097: 106,
 21103: 19,
 39071: 527,
 51670: 215,
 21109: 145,
 21113: 316,
 54039: 1440,
 21127: 92,
 42073: 301,
 21129: 53,
 21131: 141,
 21133: 292,
 21135: 59,
 21137: 64,
 21139: 26,
 39093: 232,
 54019: 135,
 21093: 631,
 39073: 66,
 42067: 40,
 51105: 108,
 39095: 1995,
 51111: 110,
 42079: 1448,
 42081: 683,
 51680: 502,
 21143: 56,
 21151: 465,
 51113: 68,
 21153: 57,
 39099: 2309,
 39101: 307,
 54049: 348,
 54051: 126,
 21159: 90,
 51690: 92,
 21161: 286,
 54053: 94,
 21145: 386,
 21147: 136,
 54047: 99,
 42083: 272,
 21165: 29,
 39107: 92,
 42053: 23,
 39069: 50,
 51093: 169,
 39087: 156,
 21155: 133,
 21157: 76,
 21149: 65,
 51117: 171,
 39105: 102,
 21167: 86,
 42085: 357,
 21077: 40,
 21123: 74,
 51678: 17,
 51091: 3,
 51103: 24,
 39097: 447,
 51115: 40,
 39103: 744,
 54057: 104,
 39111: 2,
 42089: 737,
 39113: 7798,
 42091: 369,
 51121: 691,
 42093: 13,
 39115: 107,
 54065: 40,
 39117: 198,
 21177: 143,
 39119: 225,
 51125: 94,
 51127: 105,
 51700: 1730,
 54067: 199,
 42095: 2009,
 42097: 164,
 54069: 249,
 51137: 156,
 39123: 231,
 21187: 35,
 51139: 154,
 21191: 97,
 39127: 211,
 51730: 474,
 42101: 33513,
 21195: 332,
 39131: 251,
 42103: 144,
 51735: 33,
 39133: 1263,
 51740: 841,
 54055: 587,
 39109: 458,
 51119: 30,
 21171: 114,
 21173: 230,
 21175: 58,
 21179: 148,
 39121: 5,
 51710: 1077,
 21183: 167,
 21189: 31,
 51141: 98,
 39125: 28,
 39129: 463,
 54075: 41,
 21197: 141,
 51145: 197,
 51153: 1551,
 21199: 610,
 51155: 503,
 54081: 494,
 39139: 617,
 54085: 54,
 54087: 21,
 51163: 186,
 51165: 413,
 39141: 948,
 21205: 343,
 51167: 270,
 51775: 205,
 39145: 805,
 51683: 171,
 21163: 51,
 42087: 141,
 54061: 337,
 54063: 62,
 51133: 32,
 21185: 106,
 21193: 599,
 51143: 182,
 42105: 147,
 39135: 98,
 54077: 26,
 51147: 183,
 51149: 181,
 51157: 51,
 51760: 2884,
 51770: 1103,
 21201: 19,
 21203: 198,
 21169: 78,
 54059: 180,
 42099: 160,
 39137: 38,
 21207: 122,
 39143: 158,
 42107: 733,
 51169: 353,
 39147: 225,
 39149: 383,
 51171: 369,
 21213: 93,
 51173: 310,
 42111: 187,
 51175: 94,
 51177: 716,
 21181: 90,
 51135: 89,
 54079: 188,
 51750: 144,
 21209: 178,
 51720: 3,
 54083: 36,
 21215: 40,
 39151: 2991,
 51790: 186,
 42113: 18,
 39153: 1380,
 51183: 59,
 51185: 509,
 39155: 1159,
 39157: 390,
 39159: 171,
 42119: 72,
 39161: 149,
 51810: 1537,
 51179: 583,
 21217: 202,
 42121: 291,
 21227: 620,
 42123: 213,
 51187: 427,
 42125: 881,
 21211: 124,
 42109: 132,
 51800: 245,
 54097: 253,
 39163: 52,
 39165: 842,
 39167: 366,
 51191: 321,
 21231: 229,
 39169: 449,
 42129: 1506,
 21235: 579,
 51830: 41,
 39173: 649,
 39175: 21,
 51197: 406,
 42133: 3066,
 54089: 59,
 42115: 37,
 21221: 34,
 54093: 1,
 54095: 57,
 21229: 42,
 42127: 152,
 54099: 23,
 21233: 57,
 51193: 107,
 54103: 24,
 51840: 369,
 51195: 514,
 21237: 37,
 54109: 15,
 21219: 47,
 21223: 22,
 51820: 93,
 54107: 287,
 21239: 91,
 42131: 120,
 42117: 25,
 51199: 215,
 39171: 4,
 54105: 12,
 51181: 13}

In [91]:
locations = pd.read_excel('../2019_MCMProblemC_DATA/CountyLocations.xlsx')

In [96]:
df2write = pd.DataFrame(columns=['Name', 'Code', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017'])

In [97]:
df2write

Empty DataFrame
Columns: [Name, Code, latitude, longitude, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
Index: []

In [102]:
def findLocation(name):
    for i in range(len(locations)):
        if name == locations.iloc[i]['state'] + ', ' + locations.iloc[i]['county']:
            return locations.iloc[i]['latitude'], locations.iloc[i]['longitude']
    return 0, 0
def find201x(countycode, index):
    return county2drugtotals[index].get(countycode, 0)

In [104]:
idx = 0
for c in all_counties:
    data2insert = []
    data2insert.append(countyCode2Name[c])
    data2insert.append(c)
    data2insert.append(find201x(c, 0))
    data2insert.append(find201x(c, 1))
    data2insert.append(find201x(c, 2))
    data2insert.append(find201x(c, 3))
    data2insert.append(find201x(c, 4))
    data2insert.append(find201x(c, 5))
    data2insert.append(find201x(c, 6))
    data2insert.append(find201x(c, 7))
    df2write.loc[idx] = data2insert
    idx += 1

In [105]:
df2write

,Name,Code,latitude,longitude,2010,2011,2012,2013,2014,2015,2016,2017
0,"OH, ADAMS",39001,38.839894,-83.505170,527,314,434,341,409,356,365,268
1,"OH, ALLEN",39003,40.807780,-84.057222,580,595,718,750,930,835,712,439
2,"OH, ASHLAND",39005,40.788737,-82.236039,766,744,881,872,850,1228,1202,990
3,"OH, ASHTABULA",39007,41.716723,-80.749470,571,672,1078,1066,1267,1419,1200,919
4,"OH, ATHENS",39009,39.328924,-82.101248,664,747,708,822,704,640,698,699
5,"OH, AUGLAIZE",39011,40.594219,-84.264195,184,171,250,216,222,236,251,247
6,"OH, BELMONT",39013,40.005774,-81.009752,231,425,369,647,664,583,446,503
7,"OH, BROWN",39015,38.909254,-83.883656,213,213,288,260,285,503,340,305
8,"OH, BUTLER",39017,39.423304,-84.593690,1825,1849,2053,2894,2631,2594,2706,3162
9,"OH, CARROLL",39019,40.525036,-81.092723,57,98,73,78,83,49,56,71
10,"OH, CHAMPAIGN",39021,40.172699,-83.770200,214,119,98,215,199,482,275,212
11,"OH, CLARK",39023,39.922968,-83.790596,186,114,132,354,284,608,915,1154
12,"OH, CLERMONT",39025,39.067816,-84.156634,752,890,791,803,1038,1052,1208,1432
13,"OH, CLINTON",39027,39.425987,-83.844579,455,360,431,361,492,594,542,603
14,"OH, COLUMBIANA",39029,40.778702,-80.764860,341,365,441,732,1199,1066,1315,846
15,"OH, COSHOCTON",39031,40.290568,-81.927144,75,42,86,109,101,199,204,233
16,"OH, CRAWFORD",39033,40.870591,-82.906560,218,174,412,412,618,530,515,330
17,"OH, CUYAHOGA",39035,41.430135,-81.690556,3556,3754,17801,16443,16812,15362,17469,22133
18,"OH, DARKE",39037,40.168765,-84.631372,156,203,143,200,270,262,162,225
19,"OH, DEFIANCE",39039,41.320306,-84.508483,589,431,469,728,744,875,658,570
20,"OH, DELAWARE",39041,40.231769,-82.965104,1774,1222,625,686,1035,1022,751,678
21,"OH, ERIE",39043,41.350646,-82.640448,552,689,834,1029,1329,1090,1267,972
22,"OH, FAIRFIELD",39045,39.788611,-82.641888,846,1204,1538,1715,1327,1561,1294,1030
23,"OH, FAYETTE",39047,39.583989,-83.440112,95,117,80,142,273,205,261,252
24,"OH, FRANKLIN",39049,40.028316,-83.007666,2921,5503,5546,8897,9277,8909,9594,9268
25,"OH, FULTON",39051,41.604582,-84.114105,65,118,189,128,133,223,144,182
26,"OH, GALLIA",39053,38.795246,-82.355622,416,319,207,286,374,515,516,501
27,"OH, GEAUGA",39055,41.476825,-81.185046,114,82,151,204,371,315,253,206
28,"OH, GREENE",39057,39.690821,-83.917504,964,840,846,909,1109,1384,1323,878
29,"OH, GUERNSEY",39059,40.080222,-81.485943,316,325,399,458,602,767,704,814
...,...,...,...,...,...,...,...,...,...,...,...,...
431,"VA, NORTHUMBERLAND",51133,37.931499,-76.483669,32,52,50,64,49,153,150,93
432,"VA, NOTTOWAY",51135,37.148945,-78.058393,89,112,90,104,99,112,68,105
433,"VA, ORANGE",51137,38.248812,-78.110969,156,129,198,149,173,236,176,244
434,"VA, PAGE",51139,38.600235,-78.501652,154,277,240,255,177,135,230,252
435,"VA, PATRICK",51141,36.681871,-80.284636,98,131,169,109,119,123,276,184
436,"VA, PITTSYLVANIA",51143,36.812168,-79.436411,182,192,155,224,219,280,253,224
437,"VA, POWHATAN",51145,37.553162,-77.911265,197,112,77,117,126,98,111,153
438,"VA, PRINCE EDWARD",51147,37.219307,-78.435148,183,236,211,230,231,98,158,122
439,"VA, PRINCE GEORGE",51149,37.181502,-77.215314,181,180,207,262,206,112,109,147
440,"VA, PRINCE WILLIAM",51153,38.738985,-77.553674,1551,1748,2143,2194,1964,1999,2039,2313
441,"VA, PULASKI",51155,37.058057,-80.729729,503,592,490,556,473,326,431,428
442,"VA, RAPPAHANNOCK",51157,38.692633,-78.149582,51,70,66,46,30,18,9,27
443,"VA, ROCKBRIDGE",51163,37.833180,-79.462260,186,133,253,296,266,253,306,377
444,"VA, ROCKINGHAM",51165,38.508029,-78.894944,413,460,537,646,664,476,570,651
445,"VA, RUSSELL",51167,36.933889,-82.108481,270,297,378,317,346,205,189,261
446,"VA, SCOTT",51169,36.713317,-82.596106,353,391,339,206,484,354,328,355
447,"VA, SHENANDOAH",51171,38.856559,-78.589089,369,430,347,406,405,436,427,378
448,"VA, SMYTH",51173,36.836165,-81.529883,310,193,344,272,273,237,680,662
449,"VA, SOUTHAMPTON",51175,36.695938,-77.158600,94,100,126,137,83,136,52,64
450,"VA, SPOTSYLVANIA",51177,38.188094,-77.674175,716,798,1011,775,699,710,948,844
451,"VA, STAFFORD",51179,38.416727,-77.457978,583,696,801,713,622,665,856,913
452,"VA, SURRY",51181,37.111878,-76.895924,13,14,16,12,20,0,0,17
453,"VA, SUSSEX",51183,36.909690,-77.274112,59,68,90,58,66,71,45,51
454,"VA, TAZEWELL",51185,37.123604,-81.568413,509,464,533,678,886,877,912,825
455,"VA, WARREN",51187,38.904598,-78.206107,427,505,507,503,547,431,442,443
456,"VA, WASHINGTON",51191,36.740236,-81.942167,321,474,455,406,419,361,469,517
457,"VA, WESTMORELAND",51193,38.115320,-76.756736,107,118,143,96,142,132,159,169
458,"VA, WISE",51195,37.017063,-82.610380,514,578,722,819,714,622,366,535
459,"VA, WYTHE",51197,36.911840,-81.063935,406,495,554,596,615,611,492,440
460,"VA, YORK",51199,37.223037,-76.515694,215,233,280,220,196,139,238,228

In [108]:
df2write.to_excel('totalReportsIn8YR.xlsx')